### ISSUE TITLE
Decode Error

### ISSUE THREAD

**Issue by bigboss86** [trickeyone/intl-subdivision#6]
Hi, when I get the provinces from Spain, the array is printed like this:

![Captura de pantalla de 2020-11-13 11-07-04](https://user-images.githubusercontent.com/5973407/99080687-684ffe00-25a0-11eb-91df-36327dc7b8ad.png)

**Comment by fyrye** [comment]
That appears to be [originally](https://github.com/trickeyone/intl-subdivision/blob/v1.0.0/src/Resources/data/Subdivisions.json#L1126) how all of the special characters were Unicode escaped and appear to be decoding as they were defined. Sadly, there's no real way to salvage the Unicode escape sequences easily.

Example: `M\u0087laga` is unescaped as `M‡laga` if the font supports the Unicode character.
 https://www.fileformat.info/info/unicode/char/0087/index.htm

However the correct encoding should of `Málaga` should have a Unicode escape sequence of `M\u00e1laga`

This usually happens when converting from a one charset to UTF-8, because the conversion failed or library was corrupted.
Not sure where the subdivision list came from. but for example the file output was saved in windows-1252 encoding where PHP 7+ enforces UTF-8.

**Comment by trickeyone** [comment]
The encoding has always been UTF-8. There have been a couple changes from contributors to correct some of the UTF-8 characters. I originally pulled the list from the ISO Country Codes list, then pulled their respective territories. Where I got the territories, however, I cannot recall. It's been almost 5 years since I originally created this project.

It looks like some of the unicode sequences may have been incorrect from the beginning or were corrupted during various upgrades/merges. PR that resolve these kinds of issues are always welcome.

**Comment by fyrye** [comment]
@trickeyone 
I took a shot at updating the database using an ISO subdivision library. 

I also added a build and tests for the subdivision translations from JSON to array and back.
This would allow the PHP definition to be updated, converted to JSON and the resulting `IntlSubdivision::getStatesAndProvinces()` values being asserted.

It would be a major version BC-break for the following reasons, 
- Removes the countries that do not exist in the Symfony `Intl\Countries` list.
  - `"DG": "Diego Garcia"`
- A lot of the country and subdivision codes match up, but in others the ISO database uses outdated or updated sources from your source(s).
- Additional listings in some countries
  - `"IE": {"L": "Leinster", "M": "Munster", }` (new)
- Removed listings in some countries, such as municipalities
  - `"IN": { "LA": "Ladakh" }` (old)
- Adheres to the standard ISO alpha-2 characters for appropriate subdivisions, instead of the single digit code in the current database. 
  - `"1": ...` (old) to `"01": ...` (new)
- Some of the original alpha-2 code subdivision names are different.
  - `"T": "Tarragona (Tarragona)"` (old) vs `"T": "Tarragona"` (new)  
  -  `"FK": "Falkland Islands"` (old)  to `"FK": "Falkland Islands (Malvinas)"` (new) 
  - `"SB": "Sumatera Barat"` (old) to `"SB": "Sumatra Barat"` (new)
  - `"PM": "St. Pierre & Miquelon"` (old) to `"PM": "Saint Pierre and Miquelon"`
  - ....etc

Obviously way too much to list here, thoughts?

**Comment by trickeyone** [comment]
@fyrye Please lave in the countries that don't exist. They were added to support territories and countries that don't have states (573dec4a646dfccf40beafcd5d37a6c2382c7ccc). I would prefer to not remove anything if it is not necessary. If there are updates (i.e. Tarragona), I'm fine with updating it to a more-normalized value.

It'd be easier for me to make a decision if you went ahead and created the PR. Thanks for taking a crack at this!

**Comment by fyrye** [comment]
@trickeyone only countries those that do not exist in Symfony's `Intl\Countries` were removed.

If they exist and do not have any subdivisions, they were added in the same manner as your source.
EG: `BL-BL` and `BM-BM` ([`573dec4`](https://github.com/trickeyone/intl-subdivision/commit/573dec4a646dfccf40beafcd5d37a6c2382c7ccc#diff-890ac54788aa1ef6a02d024747245471d086c8e22f76611bd607d8184b63a6f5R474))

I'll work on a pull request, but there will definitely need to be a lot of changes, since the ISO database used looks to cause more issues than it resolves, regarding BC breaks.
